### ISSUE TITLE
Ctrl Home, Ctrl END doesn't work

### ISSUE THREAD

**Issue by okbob** [TragicWarrior/libvterm#116]
I tested pspg - and looks so these combination of keywords is not handled correctly

**Comment by TragicWarrior** [comment]
I ran a simple test with the ncurses test program "demo_altkeys" and it clearly picks up that combination.  I'll have to look into why pspg doesn't.

**Comment by TragicWarrior** [comment]
Another test.  If you run pspg on a true linux terminal (tty1 - tty6 normally), CTRL + HOME has no effect.

**Comment by TragicWarrior** [comment]
I also tested with lcxterm (which you provide a link for).  It does not appear to support these key combinations.  I think the underlying problem is that the terminfo database doesn't define/support certain keystroke combinations.  I can detect the keystroke combination but the issue becomes a matter of transmitting it to the guest application.

**Comment by okbob** [comment]
út 16. 7. 2019 v 18:41 odesílatel TragicWarrior <notifications@github.com>
napsal:

> I also tested with lcxterm (which you provide a link for). It does not
> appear to support these key combinations. I think the underlying problem is
> that the terminfo database doesn't define/support certain keystroke
> combinations. I can detect the keystroke combination but the issue becomes
> a matter of transmitting it to the guest application.
>

I think so pspg uses valid technique based on tigetstr function - it
translate via tigetstr kHOM5 and kEND5. It is ncurses extension
use_extended_names.

use_extended_names https://linux.die.net/man/3/use_extended_names

Regards

Pavel

**Comment by TragicWarrior** [comment]
@okbob , this should be working with the latest commits in master.  please let me know if this issue can be closed and thanks for information on extended codes.

**Comment by okbob** [comment]
It is working well, thank you
