### ISSUE TITLE
persistent CPU usage

### ISSUE THREAD

**Issue by okbob** [TragicWarrior/libvterm#119]
I am not sure if this bug or not. I had opened vshell but without any activity but I can see some CPU usage. It is related to functions vterm_read_pipe, and is_wintouched. The CPU is relative high against fact, so there are not any activity in vshell.

**Comment by TragicWarrior** [comment]
That might be true.  The vshell program is a demo program just to show how one might implement the library.  I don't spend a lot of time on it and so it's not that intelligent.  I calls vterm_read_pipe() ever 1/30th of a second.  In a real application I would recommend the implementer using something like SIGIO to determine when to read from the pipe.

**Comment by okbob** [comment]
I wrote simple patch that reduces CPU usage after 1sec inactivity. It doesn't support more panes (but it should not be hard to support it - but it is more significant change - and I don't oriented well in your code. 
<pre>
diff --git a/vterm_read.c b/vterm_read.c
index fb244e7..a008696 100644
--- a/vterm_read.c
+++ b/vterm_read.c
@@ -1,6 +1,5 @@
 
 #include <stdlib.h>
-#include <stdio.h>
 #include <string.h>
 #include <poll.h>
 #include <errno.h>
@@ -11,6 +10,8 @@
 #include <sys/types.h>
 #include <sys/wait.h>
 #include <sys/stat.h>
+#include <sys/time.h>
+#include <unistd.h>
 
 #include "vterm.h"
 #include "vterm_private.h"
@@ -26,11 +27,12 @@
 */
 // #define MAX_PIPE_READ   (PIPE_BUF * 8)
 
+int		timeout_ms = 100;
+int		without_activity = 0;
 
 ssize_t
 vterm_read_pipe(vterm_t *vterm)
 {
-    struct pollfd   fd_array[1];
     char            *pos;
     int             bytes_peek = 0;
 	size_t			bytes_waiting = 0;
@@ -47,6 +49,9 @@ vterm_read_pipe(vterm_t *vterm)
     char            debug_file[NAME_MAX];
 #endif
 
+	fd_set			rfds;
+	struct timeval timeout;
+
     // saftey precaution
     if(vterm == NULL) return -1;
 
@@ -62,11 +67,43 @@ vterm_read_pipe(vterm_t *vterm)
         return -1;
     }
 
-    fd_array[0].fd = vterm->pty_fd;
-    fd_array[0].events = POLLIN;
+	FD_ZERO(&rfds);
+	FD_SET(STDIN_FILENO, &rfds);
+	FD_SET(vterm->pty_fd, &rfds);
+
+    timeout.tv_sec = 0;
+    timeout.tv_usec = timeout_ms * 1000;
+
+	/*
+	 * poll or select function is "expensive" with short timeout.
+	 * vterm cannot to work without timeout, because there is cycle.
+	 * untill, there is any output, then vshell doesn't send input to
+	 * panels, and without input, there is not a output. Default timeout
+	 * 10 or 30 ms is too expensive when there are not any activity.
+	 *
+	 * One possible solution is dynamic timeout. Until second after any
+	 * activity (input or output) the timeout is 10ms. Later the timeout
+	 * is 1sec. But any activity reset this timeout to 10ms again, and any
+	 * activity breaks waiting.
+	 */
+	retval = select(vterm->pty_fd + 1, &rfds, NULL, NULL, &timeout);
+
+	if (FD_ISSET(STDIN_FILENO, &rfds) || FD_ISSET(vterm->pty_fd, &rfds))
+	{
+		timeout_ms = 10;
+		without_activity = 0;
+	}
+	else
+	{
+		if (without_activity < 200)
+			without_activity += 1;
+		if (without_activity > 100)
+			timeout_ms = 5000;
+	}
+
+	if (!FD_ISSET(vterm->pty_fd, &rfds))
+		return 0;
 
-    // wait 10 millisecond for data on pty file descriptor.
-    retval = poll(fd_array, 1, 10);
 
     // no data or poll() error.
     if(retval <= 0)
</pre>

**Comment by okbob** [comment]
st 23. 10. 2019 v 18:06 odesílatel TragicWarrior <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> , This is a bit of a of a dilemma. For
> sure, poll() is expensive, but for something like VWM
> <http://www.console-craze.com/hosted-software/vwm/> which uses
> protothreads <https://github.com/LarryRuane/protothread> for
> multitasking, it's important that vterm_read() not block for any noticeable
> length of time. I think what might suit a variety of usage models is to
> modify the API allowing the caller to pass in a timeout value for poll().
> What do you think about that?
>
I am not a expert of this area - maybe there is similar solution like mine
with select with poll. Just I learned select function. If I understand
correctly to this function, it should not to block any source from list.
Similar like poll. I am not against to using poll function - but the
timeout should be longer, and I think so it have to work with infinity
timeout - if it is driven by events. But due some dependencies there, it
doesn't work with infinity timeout.

Maybe the locality of poll or select is bad. If you want to use more
terminals inside one applications (more panes), then poll should be inside
main application. It should not be inside any component. Now, you use

for term in terminals
  array[0] = term->pty;
  poll(array, 1, 10)

I am sure so it is wrong, but it is working because timeout 10ms is short.
The should be some like

for term in terminals
  array[i++] = term->pty;

poll(array, sizeof(array), 10);

You have to wait on any event from any source. Waiting on event from
specific source inside cycle requires short timeouts, and then it is
expensive - more then there are not high activity.

I don't think so possibility to pass timeout from callers can work (or it
is not enough) - it was one of ways that I tested without success. But I
have not correct mental model of libvterm. I found so it is pretty complex.
Maybe more then it is necessary. But it's maybe due some caching or some
semi asynchronous code. For me was surprising so render methods is called
from read method. I tested mtm
https://github.com/deadpixi/mtm/blob/master/mtm.c and this code is much
more simpler - but sure it support significantly less functionality. Your
libvterm significantly depends on short time repeated call of vterm_read.
When I played with longer timeouts, the interactivity was near to zero -
due some dependencies. I found only one solution (I believe so there will
be more simple solutions that I didn't find).It was based on dynamic
timeouts - after any activity was necessary to use short timeout to be sure
so user input is pushed to app, and reaction will be displayed early. With
long timeout there was not confidence, so reaction from app will be
displayed.

**Comment by TragicWarrior** [comment]
@okbob , it just occurred to me that I never checked to see but as you can see from the screenshot,  at idle, vshell consumes 0.0% CPU and 3.3% CPU in 3 pane mode with a movie playing in one.  It doesn't really seem high.  How are you measuring?
![vshell_3pane_movie](https://user-images.githubusercontent.com/8481559/67420255-e277a400-f593-11e9-8f2e-21d73b84deb7.png)
![vshell_idle](https://user-images.githubusercontent.com/8481559/67420267-e73c5800-f593-11e9-8c28-1f3fedc11ed8.png)

**Comment by okbob** [comment]
st 23. 10. 2019 v 19:52 odesílatel TragicWarrior <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> , it just occurred to me that I never
> checked to see but as you can see from the screenshot, at idle, vshell
> consumes 0.0% CPU and 3.3% CPU in 3 pane mode with a movie playing in one.
> It doesn't really seem high. How are you measuring?
> [image: vshell_3pane_movie]
> <https://user-images.githubusercontent.com/8481559/67420255-e277a400-f593-11e9-8f2e-21d73b84deb7.png>
> [image: vshell_idle]
> <https://user-images.githubusercontent.com/8481559/67420267-e73c5800-f593-11e9-8c28-1f3fedc11ed8.png>
>
> —
>
I see 0 or 0.3 after few seconds in top. Or I can run "perf top"

It is not too high - it is low. But it is +/-philosophy problem - I am
little bit nervous if some application requires CPU time when it is
absolutely idle.  It is zero problem on desktop. But can be different If I
run it on notebook with battery or on some small hw widget.

**Comment by TragicWarrior** [comment]
@okbob , please try the async-io branch.  when you start vshell, do so with the --async flag.  vshell should idle at nearly zero percent cpu for long periods of time.  fyi, this mode is only supported on linux (suppressed on FreeBSD and MacOS).

**Comment by okbob** [comment]
ne 1. 12. 2019 v 0:01 odesílatel TragicWarrior <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> , please try the async-io branch. when
> you start vshell, do so with the --async flag. vshell should idle at nearly
> zero percent cpu for long periods of time. fyi, this mode is only supported
> on linux (suppressed on FreeBSD and MacOS).
>
yes, great work - I don't see vshell in top more.

Thank you
