### ISSUE TITLE
strange display inside vshell after export command

### ISSUE THREAD

**Issue by okbob** [TragicWarrior/libvterm#133]
inside vshell run command:

    export ___PAGER=kkkk

this statement should do nothing in bash, but I see repeated string `=kkkk` before prompt
![Snímek z 2019-08-28 20-31-20](https://user-images.githubusercontent.com/546675/63882720-ded00280-c9d2-11e9-895b-39d074fc76c8.png)

**Comment by TragicWarrior** [comment]
@okbob , take a look at branch ```bash-private-osc-fix``` and see if it fixes the problem.  i was able to reproduce the problem and the fix i put in this branch addressed it for me.

**Comment by okbob** [comment]
this fix is successful.  Thank you

**Comment by okbob** [comment]
fixed, thank you
