### ISSUE TITLE
Alt keywords doesn't work

### ISSUE THREAD

**Issue by okbob** [TragicWarrior/libvterm#150]
I am testing pspg in vshell and ALT keywords doesn't work now.

Alt m - enable/disable mouse
Alt c - enable/disable cursor

looks like ALT is processed always by vshell and is not propagated to application.

**Comment by TragicWarrior** [comment]
@okbob , this looks like a long standing issue with the library and not the demo program itself.  i will try to address it this week if possible.

**Comment by TragicWarrior** [comment]
@okbob , please test branch "multi-key-fix".  it fixes the problem for me.

**Comment by okbob** [comment]
pá 13. 12. 2019 v 22:32 odesílatel TragicWarrior <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> , please test branch "multi-key-fix".
> it fixes the problem for me.
>

unfortunately - it doesn't help to pspg

I try Alt-n .. show/hide row numbers

**Comment by TragicWarrior** [comment]
@okbob , I am testing with both alt-n and alt-m on Fedora 31 and Xubuntu 18.04.3 LTS and the keys work as expected.  can you tell me more about your environment?

![alt_keys_working](https://user-images.githubusercontent.com/8481559/70949347-2bdbf100-2023-11ea-8694-a372ea418155.png)

**Comment by okbob** [comment]
po 16. 12. 2019 v 23:43 odesílatel TragicWarrior <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> , I am testing with both alt-n and
> alt-m on Fedora 31 and Xubuntu 18.04.3 LTS and the keys work as expected.
> can you tell me more about your environment?
>
> [image: alt_keys_working]
> <https://user-images.githubusercontent.com/8481559/70949347-2bdbf100-2023-11ea-8694-a372ea418155.png>
>

Usually I use two terminals - gnome-terminal and terminator

<https://user-images.githubusercontent.com/8481559/70949347-2bdbf100-2023-11ea-8694-a372ea418155.png>

**Comment by okbob** [comment]
út 17. 12. 2019 v 6:46 odesílatel Pavel Stehule <pavel.stehule@gmail.com>
napsal:

>
>
> po 16. 12. 2019 v 23:43 odesílatel TragicWarrior <notifications@github.com>
> napsal:
>
>> @okbob <https://github.com/okbob> , I am testing with both alt-n and
>> alt-m on Fedora 31 and Xubuntu 18.04.3 LTS and the keys work as expected.
>> can you tell me more about your environment?
>>
>> [image: alt_keys_working]
>> <https://user-images.githubusercontent.com/8481559/70949347-2bdbf100-2023-11ea-8694-a372ea418155.png>
>>
>
> Usually I use two terminals - gnome-terminal and terminator
>

It is works. I repeated tests and I rerun cmake again. In new build all is
working well.

Still there is small issue - Alt mouse click doesn't work - but common Alt
combinations is working.

Thank you

Pavel

**Comment by TragicWarrior** [comment]
@okbob , alt-mouse is very different issue.  thanks for retesting.  closing.
