### ISSUE TITLE
slow draw on Fedora Core 29

### ISSUE THREAD

**Issue by okbob** [TragicWarrior/libvterm#42]
pspg is displayed without unwanted artefacts, but slowly. When I used theme with just black/white colours - the redraw is significantly faster.

**Comment by TragicWarrior** [comment]
@okbob , after some profiling, I found that the pair_content() call from ncursesw is about 7x slower on Fedora 29 vs Bionic.  i don't know exactly why, but it gave me an opportunity to create some new interfaces (which I had been meaning to do anyway).  the vshell demo program takes advantage of this interface to provide fast color extraction.  the commit is in master now.  give it a try and let me know.

**Comment by okbob** [comment]
Now, it almost perfect :). This issue is fixed, thank you.

So, add mouse support and true colors and vshell will be perfect terminal. I though more about some combination console application and my ncurses st-menu based application to get some "rich" terminal applications.

Note: the slow pair_content can be reported as bug to bug-ncurses. FC uses the most fresh ncurses, and I remember, there was some changes maybe related to true colour support.

**Comment by TragicWarrior** [comment]
@okbob , please feel free to chime in on the bug report email thread.

I took a look at st-menu and it looks really nice.  libvterm is a small part of a larger system I wrote which is a window manager for the console that i've written.  you might want to take a look.

http://www.console-craze.com/hosted-software/vwm/
a really OLD video of it in action can be found here
https://www.youtube.com/watch?v=aJAaeWRLBJU

VWM is written on top of a C library I wrote called libviper and it has some basic classes in it.  It's been a slow effort because I was trying to avoid using MENU and PANEL objects since their not found in other curses implementations.  I've gotten past that mostly now and can start building more 'classful' widgets now.  Maybe I'll take some inspiration from st-curses :)

**Comment by okbob** [comment]
pá 28. 12. 2018 v 16:53 odesílatel TragicWarrior <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> , please feel free to chime in on the
> bug report email thread.
>
> I took a look at st-menu and it looks really nice. libvterm is a small
> part of a larger system I wrote which is a window manager for the console
> that i've written. you might want to take a look.
>
> http://www.console-craze.com/hosted-software/vwm/
> a really OLD video of it in action can be found here
> https://www.youtube.com/watch?v=aJAaeWRLBJU
>
I tested there already - and I had it in my bookmarks.

I like terminal applications - like mc, or psql. But sometimes it has nice
face (I remember of some nice MSDOS applications) or sometimes are too
simply.

psql terminal is great, but doesn't allow new commands and some task can be
started better from menu or from some forms. So my idea is to have some
shell - bash, psql, ...  with possibility to start some actions from custom
menu by F2 like mc - or with menu bar. But I found so integration any
terminal application into ncurses application is pretty hard - but with
libvterm it is possible. So I am impressed from your work. I tested some
other libraries, but the stability and functionality was not great.


> VWM is written on top of a C library I wrote called libviper and it has
> some basic classes in it. It's been a slow effort because I was trying to
> avoid using MENU and PANEL objects since their not found in other curses
> implementations. I've gotten past that mostly now and can start building
> more 'classful' widgets now. Maybe I'll take some inspiration from
> st-curses :)
>
with pleasure :). I wrote st-menu because I didn't find any library that
was simple to use and with good look. Unix terminals, ncurses are pretty
strong but without modern and practical libraries. Now I am think about
some similar but for forms (dialogs). I like mc, Borland Turbo Vision look
but I would not to write framework.

These libraries are prototypes (I learned ncurses) - I designed it for pspg
- but it has design that I expect and works almost well. People use it on
Linux, BSD, MacOS.

**Comment by TragicWarrior** [comment]
@okbob , there's a commit i master that you might want to try.  i implemented a gclock lru to cache color mappings and it seems to have improved overall performance by about 5% on top of what I already applied earlier for this issue.
