### ISSUE TITLE
double escape is necessary

### ISSUE THREAD

**Issue by okbob** [TragicWarrior/libvterm#58]
Relative unfriendly is necessity to press escape 2x - probably better to bypass processing of Alt (escape) chars.

**Comment by TragicWarrior** [comment]
@okbob , can you explain this a bit.  I routinely test libvterm with links, iptraf-ng, and alsamixer.  All of these applications have important functionality tied to pressing the ESC key and I have no problem with them.

**Comment by okbob** [comment]
I did recheck, and it is working, I am sorry. It is slower, and it was reason why I though it is broken - maybe you should to set set_escdelay to some low value - or disable this key processing - because same will be processed in nested applications. Now there are 2x applied ESCDELAY.

**Comment by TragicWarrior** [comment]
@okbob , 

set_escdelay is a ncurses only extension.  my long term goal is to support libvterm on other curses implementations (like pdcurses).  let me give it some thought.

**Comment by okbob** [comment]
út 1. 1. 2019 v 17:59 odesílatel TragicWarrior <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> ,
>
> set_escdelay is a ncurses only extension. my long term goal is to support
> libvterm on other curses implementations (like pdcurses). let me give it
> some thought.
>

maybe you can use ESCDELAY variable

**Comment by TragicWarrior** [comment]
@okbob , I would speculate that ESCDELAY is also ncurses specific.

**Comment by okbob** [comment]
út 1. 1. 2019 v 18:26 odesílatel TragicWarrior <notifications@github.com>
napsal:

> @okbob <https://github.com/okbob> , this isn't something that libvterm
> can actually implement. i can put something into the demo program, but
> libvterm doesn't perform the job of fetching keystrokes from the keyboard.
> that's actually the responsibility of the integrator using the library.
> take a look at the bottom of main in demo/vshell.c and you will see the
> processing loop for input.
>
It has sense. I am sorry. I don't differ between libvterm and vshell.

On second hand - can be nice, if vshell can be used very well with all
properties - and then the code of vshell can be very good (and almost
final) example of libvterm usage.

**Comment by TragicWarrior** [comment]
@okbob , yes.  the purpose of the vshell demo program is to show what vshell can do but also give an example as to how to use the features of the library.
